name: MSBuild

on:
  push:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  PUBLISH_OUTPUT_DIRECTORY: "bin/Publish"

permissions:
  contents: read

jobs:
  build:
    runs-on: ASPNET-FRAMEWORK-WEB-RUNNER

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /t:Build /p:Configuration=${{env.BUILD_CONFIGURATION}} 

    - name: Publish
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="Any CPU" /p:outdir=${{env.PUBLISH_OUTPUT_DIRECTORY}}
    
    - name: Copying files to application directory
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: xcopy .\SampleAspNetFrameworkWeb\bin\Publish\_PublishedWebsites\SampleAspNetFrameworkWeb D:\AspNetFrameworkWeb /y /s /e /h
    

      
      

